## reference: http://docs.travis-ci.com/user/languages/r/
language: r
cache: packages
latex: false
warnings_are_errors: false
r_build_args: --no-build-vignettes
r_check_args: --as-cran --ignore-vignettes

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_: false
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

r_packages:
  - covr
# This is the minimal set of R packages needed to run "R CMD check" on
# the package.
  - data.table
  - curl
  - jsonlite
  - stringr
  - utils
  - SummarizedExperiment
  - ggplot2
  - httr
  - RMySQL
  - DBI
  - PupillometryR
  - ggpubr
  - ggridges
  - viridis
  - GenomeInfoDb
  - IRanges
  - ggrepel
  - GenomicRanges
  - tidyr
  - BiocGenerics
  - methods
  - cowplot
  - R.utils

r_github_packages: dingruofan/xQTLbiolinks

after_success:
  - Rscript -e 'library(covr); codecov()'

notifications:
  email:
  recipients: 21620170155349@stu.xmu.edu.cn
  on_success: never
  on_failure: always
