---
title: "basic-manual"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{basic-manual}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(GTExbiolinks)
library(data.table)
library(ggplot2)
library(ggridges)
library(viridis)
library(SummarizedExperiment)
```


```{r warning=FALSE, message=FALSE}
# set.seed(111)
# a <- proT$geneSymbol[sample(1:nrow(proT), 14,replace = FALSE)]
genes=c("FNDC8", "S100Z", "AQP6", "AMOT", "C3orf38", "FOXL1", "COX11", "FCN3", "DDX58", "CFI", "MS4A18", "NUDT13", "HOXA4", "VSX1")
expProfiles <- GTExdownload_exp(genes=genes, geneType = "geneSymbol", tissueSiteDetail = "Lung", "gtex_v8", toSummarizedExperiment=TRUE)
expData <- as.data.table(cbind( data.table(geneSymbol=rownames(expProfiles)), assay(expProfiles) ))
expData1 <- melt(expData, id.vars="geneSymbol", variable.name = "sampleId", value.name="exp")
ggplot( expData1, aes(x = log(exp+1,10), y = reorder(geneSymbol, -exp, median), fill = ..density..))+
  geom_density_ridges_gradient( gradient_lwd = 1, scale = 1.4, rel_min_height = 0.05, size = 0.3) +
  # scale_fill_gradientn( colours = colorRampPalette(c("white", "blue", "red"))(27) )+
  scale_fill_viridis(name = "WCAE per SOC", option = "C")+
  xlab("Gene expression (log(TPM+1))")+
  ylab("Gene symbol")+
  theme_bw()+
  theme( legend.title = element_blank())

```
```{r}
# 一个基因在多个组织中的表达：


```

```{r}
library(ggpubr)
gene2 = c("AMOT", "HOXA4")
expProfiles <- GTExdownload_exp(genes=gene2, geneType = "geneSymbol", tissueSiteDetail = "Lung", "gtex_v8", toSummarizedExperiment=TRUE, pathologyNotesCategories = TRUE)
expData <- as.data.table(cbind( data.table(geneSymbol=rownames(expProfiles)), assay(expProfiles) ))
expData2 <- as.data.frame(t(expData[geneSymbol %in% gene2][,-c("geneSymbol")]))
colnames(expData2) <- gene2

sampleInfo <- as.data.table(colData(expProfiles))
expData2 <- cbind(sampleInfo[rownames(expData2), on="sampleId"][,c("sampleId", "sex")], expData2)

ggscatterhist(expData2, x=gene2[1], y=gene2[2], 
              shape = 21, color = "sex", fill="sex",
              margin.plot="density",
              margin.params = list(fill="sex", color="black", size=0.2),
              legend = c(0.9,0.15),
              ggtheme = theme_minimal())
```

```{r}
library(PupillometryR)
gene="KIF15"
geneEqtl <- GTExdownload_eqtlSig(gene=gene, datasetId="gtex_v8")
geneEqtlSub <- geneEqtl[,.(variantId, tissueSiteDetail, pValue)]
geneEqtlSub$logP <- -log(geneEqtlSub$pValue, 10)
setDF(geneEqtlSub)
ggplot(geneEqtlSub, aes(x=reorder(tissueSiteDetail, -logP, median),y=logP))+
  geom_flat_violin(data=geneEqtlSub, mapping=aes(fill=tissueSiteDetail), position=position_nudge(x=0.25), color="black", scale = "width")+
  geom_jitter(aes(color=tissueSiteDetail), width = 0.1)+
  geom_boxplot(width=0.15, position = position_nudge(x=0.25), fill="white", size=0.1)+
  coord_flip()+
  ylab("log(Pvalue) of eQTL")+
  xlab("")+
  theme_bw()+
  guides(fill="none", color="none")
```

