---
title: "ColocAnalysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ColocAnalysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This vignette shows a complete workflow of colocalization analysis with your own GWAS data using GTExbiolinks.

```{r setup}
library(GTExbiolinks)
```

```{r}
# Step 1: download GWAS example file.
gwasFile <- tempfile(pattern = "file")
gwasURL <- "http://bioinfo.szbl.ac.cn/finalColoc/tmp/gwasFile/gwasChr6Sub1.txt"
utils::download.file(gwasURL, destfile=gwasFile)
# If your dataset provides the standard error, simply square it to get the variance.
gwasDF <- data.table::fread(gwasFile, sep="\t", header=TRUE)
gwasDF
```

```{r fig.width=6.1, fig.height=4.7}
# Step 2: fetch all regulatory associations of variants for interesting gene, like "RP11-385F7.1" in this example.
traitGene="RP11-385F7.1"
tissueSiteDetail="Lung"
geneAsso<-  GTExvisual_eqtlTrait(traitGene, tissueSiteDetail=tissueSiteDetail)
```

```{r}
geneAsso <- geneAsso[,.(snpId, pValue, maf)] 
geneAsso
```

```{r}
# Step 3: merge gwas and eqtl datasets by SNP ID. Centered on the SNP with the lowest pValue, sentinel snps within one million bases are retained.
gwas_eqtl <- merge(gwasDF[,.(snpId=rsid, pValue=P, maf=maf, position)], geneAsso, by="snpId", sort=FALSE, suffixes = c(".gwas",".eqtl"))
centerSnp <- gwas_eqtl[which.min(gwas_eqtl$pValue.gwas),]
colocRange=1e6
sentinelSnps <- gwas_eqtl[position>=(centerSnp$position-(colocRange)/2) & position<=(centerSnp$position+(colocRange)/2),]
sentinelSnps
```

```{r}
# Step 4: conduct colocalization analysis using coloc package.
library(coloc)
colocResult <- coloc.abf(
  dataset1=list(
    pvalues=sentinelSnps$pValue.gwas, type="quant", N=50000, MAF=sentinelSnps$maf.gwas),
 dataset2=list(
   pvalues=sentinelSnps$pValue.eqtl, type="quant", N=600,
   MAF=sentinelSnps$maf.gwas))
colocResult
```

```{r fig.width=6.1, fig.height=4.7}
# Step 5: visualize GWAS-eQTL colocalization for selected gene. 
eqtlAsso2 <-  GTExvisual_eqtlGWAS(sentinelSnps[,c("snpId","pValue.gwas")], traitGene="RP11-385F7.1", tissueSiteDetail="Lung")
```

```{r fig.width=6.1, fig.height=4.7}
# Or you can using locuscomparer package for visualization of GWAS-eQTL colocalization.
library(locuscomparer)
locuscompare( sentinelSnps[,.(rsid=snpId, pval=pValue.gwas)], sentinelSnps[,.(rsid=snpId, pval=pValue.eqtl)] )
```
